server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/angularspring
    password: 12345678
    username: anand
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
secret-key: 'mysecret'